config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/new'

  root 'projects#index'
  resources :projects
  resources :tasks

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def create
    @project = Project.create(project_params)

  end

  def edit
  end

  def update
    @project.update(project_params)
  end

  def destroy
    @project.destroy
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
	
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:edit, :update, :destroy]

	def create
		@task = Task.create(task_params)
	end

	def edit
  end

  def update
    @task.update(task_params)
  end

	def destroy
    @task.destroy
  end

	private

	def find_task
		@task = Task.find(params[:id])
	end

	def task_params
		 params.require(:task).permit(:name, :project_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title Todo
    = stylesheet_link_tag    'application',  media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/projects/_form.html.haml
= simple_form_for @project, remote: true do |f|
  = f.input :name, label: false

app/views/projects/_project.html.haml
%li{id: "js-project_#{project.id}"}
  .panel.panel-primary
    .panel-heading#project-panel
      %span{id: "js-project_#{project.id}_name"}= project.name
      %span#project-actions
        = link_to project, remote: true, method: :delete,
        data: { confirm: 'Are you sure?' } do
          %i.glyphicon.glyphicon-trash
        = link_to edit_project_path(project), remote: true do
          %i.glyphicon.glyphicon-pencil



    .panel-body
      = simple_form_for :task, :url => tasks_url, remote: true do |f|
        = f.hidden_field :project_id, value: project.id
        = f.input_field :name, label: false
        = f.submit 'Add Task', class: 'btn btn-success'


  %ul{id: "js-project_#{project.id}_tasks"}= render project.tasks

app/views/projects/create.js.haml
$('#js-projects').append("#{j(render 'project', project: @project)}");
$("#project-form").slideDown(350);

app/views/projects/destroy.js.haml
$("#js-project_#{@project.id}").remove();

app/views/projects/edit.js.haml
$("#js-project_#{@project.id}_name").html("#{j(render 'form')}");

app/views/projects/index.html.haml
.col-md-6.col-md-offset-3
  %ul#js-projects= render @projects

= simple_form_for :project, url: projects_url, html: {class: 'col-md-6 col-md-offset-5'},
remote: true do |f|
  = f.hidden_field :name, value: 'New TODO List'
  = f.button :button, class: 'btn btn-primary', id: '#new-project' do
    %span.glyphicon.glyphicon-plus Add TODO List

app/views/projects/update.js.haml
$("#js-project_#{@project.id}").html("#{j(render 'project', project: @project)}");

app/views/tasks/_form.html.haml
= simple_form_for @task, remote: true do |f|
  = f.input :name, label: false

app/views/tasks/_task.html.haml
%li{id: "js-task_#{task.id}"}
  %table.table.table-bordered.table-hover
    %tbody
      %tr
        %td.col-md-1
          %input{type: "checkbox", id: "checkbox"}
        %td.col-md-9
          %span{id: "js-task_#{task.id}_name"}= task.name
        %td
          %span#task-actions
            = link_to task, remote: true, method: :delete do
              %i.glyphicon.glyphicon-trash
            = link_to edit_task_path(task), remote: true do
              %i.glyphicon.glyphicon-pencil

app/views/tasks/create.js.haml
$("#js-project_#{@task.project_id}_tasks").append("#{j(render 'task', task: @task)}");

app/views/tasks/destroy.js.haml
$("#js-task_#{@task.id}").remove();

app/views/tasks/edit.js.haml
$("#js-task_#{@task.id}_name").html("#{j(render 'form')}");

app/views/tasks/update.js.haml
$("#js-task_#{@task.id}").html("#{j(render 'task', task: @task)}");

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.erb